# Sample configuration
# This use default values, except for settings with "***"

# Barry will watch this directory, looking for new backups.
queue_path = "var/queue"

# Barry will keep its data in this directory. It includes internal databases
# but also local cold storage cache, so you will need free space here.
# You must use the same "system storage partition" as queue_path, because Barry
# will move large files from queue_path to local_storage_path.
local_storage_path = "var/storage"

# Maximum files to upload at the same time
# warning: required memory = num_uploaders * chunk_size (at least)
num_uploaders = 2

# Default file expiration settings, it's possible to change this at project
# level using the client.
#
# - format: keep XX [day(s)|year(s)] every YY [day|file]
# - if no "every" part is given, it's the default whatever the day/file
# - longest value wins, of course
#
# Notes :
# - for "multi-files" backups, prefer to use "day" instead of "file"
# - a "day" stops at midnight, watchout for backups close to midnight.
# - changing these settings does not impact existing projets!
[expiration]
local = [
    "keep 30 days",
]
remote = [
    "keep 30 days",
    "keep 90 days every 7 file",
#    "keep 1 year every 90 day",
]


# Swift API settings, currently tested only with auth V3 style, older
# versions and environment reading are in the TODO.
[swift]
username = "***"
api_key = "***" # "password" in older auth
auth_url = "***"
domain = "Default" # specific to V3 auth
region = "***"
container = "***"
chunk_size = "512M" # large objects are split
